version: '2'
services:
  web:
    image: php:7.2-apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
  db:
    image: mysql:5.7
    environment:
      ['MYSQL_ROOT_PASSWORD=secret']
    ports:
      - 3306:3306
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION